set.seed(20250411)
stress <- units::set_units(100, MPa)
temperature <- units::set_units(300, degC)
pressure <- units::set_units(400, MPa)
fugacity <- ps_fugacity(pressure, temperature)

creep_quartz(stress = stress, temperature = temperature, model = "Paterson1990")
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Hirth2001") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Rutter2004") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Lu2019") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Kronenberg1984") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Luan1992") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Gleason1995") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Rutter2004") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Fukuda2018_LT") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Richter2018") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, model = "Tokle2019_LT") |>  quantile()
creep_quartz(stress = stress, temperature = temperature, fugacity = fugacity, pressure = pressure, model = "Lusk2021_LP") |>  quantile()
